# see for more details:
# https://github.com/argoproj/argo-helm/blob/main/charts/argo-events/values.yaml
## Event bus configuration
argo-events:
  configs:
    ## NATS event bus
    nats:
      # -- Supported versions of NATS event bus
      versions:
        - version: 0.22.1
          natsStreamingImage: nats-streaming:0.22.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3

    ## JetStream event bus
    jetstream:
      # Supported versions of JetStream eventbus
      versions:
        - version: "2.8.1"
          natsImage: nats:2.8.1
          metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3
          configReloaderImage: natsio/nats-server-config-reloader:0.6.3
          startCommand: /nats-server
